openapi: 3.0.3
info:
  title: VSX order service
  description: Microservice handling order database in VSX project
  version: 1.0.0
servers:
  - url: http://localhost:9003
    description: Development server

paths:

  /order/{orderId}:
    parameters:
      - name: orderId
        in: path
        schema:
          type: int
        example: 1
        description: id of the order

    post:
      summary: Create an order
      requestBody:
        description: Order to create
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/order'
      responses:
        400:
          description: OrderId in path and body doesn't match
        409:
          description: OrderId already used
        201:
          description: Order created

    get:
      summary: Read an order
      responses:
        404:
          description: Order not found
        200:
          description: Found order
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/order'

    put:
      summary: Update an order
      requestBody:
        description: New values of the order
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/order'
      responses:
        400:
          description: OrderId in path and body doesn't match
        404:
          description: Oder not found
        200:
          description: Order updated

    delete:
      summary: Delete an order
      responses:
        404:
          description: Order not found
        200:
          description: Order deleted

components:
  schemas:
    order:
      type: object
      properties:
        orderId:
          type: integer
        compteId:
          type: integer
        titreId:
          type: integer
        status:
          type: string
        typeOrder:
          type: string
        coteOrder:
          type: string
        prixLimit:
          type: number
      example:
        orderId: 1
        compteId: 1
        titreId: 1
        status: nouveau
        typeOrder: LIMIT
        coteOrders: Acheteur
        prixLimit: 10.0